version: "3.9"
services:
  web:
    build: .
    ports:
      - "3005:3005"
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - SERVER=${SERVER}
      - DATABASE=${DATABASE}
    volumes:
      - /usr/src/app/node_modules
    command: npm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./db/src/app/fec